// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rolling_gaussian_cpp
List rolling_gaussian_cpp(NumericVector x, double sigma, double threshold);
RcppExport SEXP _openair_rolling_gaussian_cpp(SEXP xSEXP, SEXP sigmaSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_gaussian_cpp(x, sigma, threshold));
    return rcpp_result_gen;
END_RCPP
}
// distEuclid
NumericMatrix distEuclid(NumericMatrix Am, NumericMatrix Bm);
RcppExport SEXP _openair_distEuclid(SEXP AmSEXP, SEXP BmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Am(AmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Bm(BmSEXP);
    rcpp_result_gen = Rcpp::wrap(distEuclid(Am, Bm));
    return rcpp_result_gen;
END_RCPP
}
// distAngle
NumericMatrix distAngle(NumericMatrix Lonm, NumericMatrix Latm);
RcppExport SEXP _openair_distAngle(SEXP LonmSEXP, SEXP LatmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Lonm(LonmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Latm(LatmSEXP);
    rcpp_result_gen = Rcpp::wrap(distAngle(Lonm, Latm));
    return rcpp_result_gen;
END_RCPP
}
// rolling_average_cpp
List rolling_average_cpp(NumericVector x, int width, std::string alignment, double threshold, std::string statistic, Nullable<NumericVector> probs);
RcppExport SEXP _openair_rolling_average_cpp(SEXP xSEXP, SEXP widthSEXP, SEXP alignmentSEXP, SEXP thresholdSEXP, SEXP statisticSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< std::string >::type alignment(alignmentSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< std::string >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_average_cpp(x, width, alignment, threshold, statistic, probs));
    return rcpp_result_gen;
END_RCPP
}
// dateAggregate
DataFrame dateAggregate(DataFrame df, std::string date_col, std::string statistic, double threshold, double probs);
RcppExport SEXP _openair_dateAggregate(SEXP dfSEXP, SEXP date_colSEXP, SEXP statisticSEXP, SEXP thresholdSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type date_col(date_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(dateAggregate(df, date_col, statistic, threshold, probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_openair_rolling_gaussian_cpp", (DL_FUNC) &_openair_rolling_gaussian_cpp, 3},
    {"_openair_distEuclid", (DL_FUNC) &_openair_distEuclid, 2},
    {"_openair_distAngle", (DL_FUNC) &_openair_distAngle, 2},
    {"_openair_rolling_average_cpp", (DL_FUNC) &_openair_rolling_average_cpp, 6},
    {"_openair_dateAggregate", (DL_FUNC) &_openair_dateAggregate, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_openair(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
