# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Rolling Gaussian Smoother
#' @param x Numeric vector to smooth
#' @param sigma Standard deviation of the Gaussian kernel
#' @param threshold Min fraction of valid data in window (0-1)
#' @keywords internal
rolling_gaussian_cpp <- function(x, sigma, threshold = 0.5) {
    .Call(`_openair_rolling_gaussian_cpp`, x, sigma, threshold)
}

#' Calculate Euclidean distance for trajectories
#' @export
#' @keywords internal
distEuclid <- function(Am, Bm) {
    .Call(`_openair_distEuclid`, Am, Bm)
}

#' Distance matrix based on similarity of trajectory angles
#' @export
#' @keywords internal
distAngle <- function(Lonm, Latm) {
    .Call(`_openair_distAngle`, Lonm, Latm)
}

#' @keywords internal
rolling_average_cpp <- function(x, width, alignment, threshold, statistic = "mean", probs = NULL) {
    .Call(`_openair_rolling_average_cpp`, x, width, alignment, threshold, statistic, probs)
}

dateAggregate <- function(data, date_col = "date", statistic = "mean", threshold = 0.0, probs = as.numeric( c(0.5))) {
    .Call(`_openair_dateAggregate`, data, date_col, statistic, threshold, probs)
}

