# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Euclidean distance for trajectories
#' @export
distEuclid <- function(Am, Bm) {
    .Call(`_openair_distEuclid`, Am, Bm)
}

#' Distance matrix based on similarity of trajectory angles
#' @export
distAngle <- function(Lonm, Latm) {
    .Call(`_openair_distAngle`, Lonm, Latm)
}

#' Rolling Average with Threshold
#' @param x A numeric vector
#' @param width Integer window width
#' @param alignment String: "left", "centre", or "right"
#' @param threshold Numeric fraction (0-1) of non-NA data required
#' @export
rolling_average_cpp <- function(x, width, alignment, threshold) {
    .Call(`_openair_rolling_average_cpp`, x, width, alignment, threshold)
}

